### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ptvrajsk** [cs3237-HydrationMonitor/hydro_mobile#1]
# Things to do
- [ ] MQTT Connection to AWS
- [ ] Receive data from AWS (Querying for data state & Receiving updates in Real Time)
- [ ] Clean up UI, make it look abit cool I guess
